version: '3.8'
services:
  db:
    container_name: drf_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: letter_db

    ports:
      - "5437:5432"


  pgadmin:
    container_name: drf_db_1
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5057:80"
